#!/data/data/com.termux/files/usr/bin/bash
#WorkShopDownloader #创意工坊下载器
clear
echo "作者:樂卟嘶屬  Q群:614255348"
echo "请输入创意工坊的模组ID或URL："
read INPUT
if [ ! $INPUT ] ; then
echo "无法识别ID或URL，啥也没发生！"
exit
fi
steam_id=`echo $INPUT | sed 's/http.*id=\([0-9]*\)&.*/\1/'`
json=`wget -qO- "https://5.5w.pw/api?mid=$steam_id"`
title=`echo $json | sed 's/.*"title":"\([^,}]*\)".*/\1/'`
url=`echo $json | sed 's/.*"url":"\([^,}]*\)".*/\1/'`
url=`echo $json | sed 's/.*"code":\([^,}]*\).*/\1/'`
if [ ! $code==404 ] ; then
printf "开始下载……\n"
printf "title：$title\n"
printf "url：$url\n"
wget -qO "/sdcard/download/[M]$title.ZIP" "$url"
printf "下载完成，已保存文件/sdcard/download/[WSD]$title.ZIP\n"
else
printf "下载失败！输入的ID或URL有误！\n"
fi